### ISSUE TITLE
Map "Mistlock Sanctuary" is wrongfully considered as "Fractals of the Mists"

### ISSUE THREAD

**Issue by nakami** [Maselkov/GW2RPC#12]
While being on the map ["Mistlock Sanctuary"](https://wiki.guildwars2.com/wiki/Mistlock_Sanctuary) (a lounge type of map with NPCs), GW2RPC considers this map as "Fractals of the Mists" and displays that kind of game content whlist it probably should be seen as its own map.

![image](https://user-images.githubusercontent.com/6167914/134716996-aa7548ec-14d5-499f-af0a-f3a448887533.png)

**Comment by n1tr0-5urf3r** [comment]
The map_id of Mistlock Observatory was changed by anet from 872 to 1206. The registry will be updated soon :)

**Comment by n1tr0-5urf3r** [comment]
> 
> 
> Just to make sure: Don't confuse ["Mistlock Observatory"](https://wiki.guildwars2.com/wiki/Mistlock_Observatory) with ["Mistlock Sanctuary"](https://wiki.guildwars2.com/wiki/Mistlock_Sanctuary) ([map_id 1206](https://api.guildwars2.com/v2/maps/1206)).
> ## Mistlock Observatory
> 
> Friendlist for others when I am in Mistlock Observatory: ![image](https://user-images.githubusercontent.com/6167914/137599299-0d5b7b48-7e86-40ba-9ecb-17c305643d02.png)
> 
> GW2RPC when I am in Mistlock Observatory: ![image](https://user-images.githubusercontent.com/6167914/137599184-fb486ef3-c2af-4075-ab4e-fd03090ccb58.png)
> ## Mistlock Sanctuary
> 
> Friendlist for others as I am in Mistlock Sanctuary: ![image](https://user-images.githubusercontent.com/6167914/137599104-94f5be82-be2f-4ffc-876a-4492df331fe4.png)
> 
> GW2RPC when I am in Mistlock Sanctuary: ![image](https://user-images.githubusercontent.com/6167914/137599206-be0500da-e309-4e20-af43-74b157b11c81.png)
> ## gw2rpc api
> 
> In the registry, Mistlock Observatory exists, while Sanctuary does not: https://gw2rpc.info/api/v2/registry
> 
> ```json
> {
>   "fractals": [
>     {
>       "id": 872, 
>       "name": "Mistlock Observatory"
>     },
> ```

You are totally right, I confused both but I actually was talking about the same. Someone actually reported the same issue on our discord support server :) Need Maselkov to update the website registry though, I don't have access there.

**Comment by n1tr0-5urf3r** [comment]
Solved
