### ISSUE TITLE
Provide development instructions

### ISSUE THREAD

**Issue by nakami** [Maselkov/GW2RPC#13]
Hey! I was trying to run the code on Win10 with Python Version 3.8.10 with the requirements installed and got this error:

`FileNotFoundError: [Errno 2] No translation file found for domain: 'base'`

I was using `locales_path = resource_path("./locales")` and `locales_path = resource_path("../locales")` each without success. I also compiled gw2rpc myself with pyinstaller and both `locales_path` each and the same error occurred.

Also, please provide more development instructions:

- which Python Version(s) are supported to run/build
- how to call pyinstaller (arguments)

**Comment by n1tr0-5urf3r** [comment]
#14
