### ISSUE TITLE
Multilanguage Support

### ISSUE THREAD

**Issue by Masiero2012** [Maselkov/GW2RPC#3]
Hello Can you make a Multilanguage support by extra text file 

i love this Project but i was not good in python

**Comment by Masiero2012** [comment]
sry wrong klick

**Comment by Maselkov** [comment]
It's gonna require a lot of changes, but hopefully be done at some point

**Comment by Zalatis** [comment]
If you adapt the code with a json or something like this for a nice multilanguage support I can help for the french translation ;)

**Comment by jusdepatate** [comment]
I can help too ;)

**Comment by n1tr0-5urf3r** [comment]
> 
> 
> Hello Can you make a Multilanguage support by extra text file
> 
> i love this Project but i was not good in python

This is implemented in #11

**Comment by Maselkov** [comment]
#11
