### ISSUE TITLE
[2.51] Installer won't auto detect GW2 install directory

### ISSUE THREAD

**Issue by Dave247** [Maselkov/GW2RPC#31]
The default installer path uses the folder name `GW2RPC` in the game's addon directory, however this causes a problem when trying to run as the program is instead expting to be located in the `RPC` folder instead, as indicated by this error message.
![image](https://user-images.githubusercontent.com/10183015/200980282-5532a4a6-b5ca-4ce0-86a4-8a4df25f0dfe.png)

**Comment by n1tr0-5urf3r** [comment]
The error message might be a bit misleading, the folder name can actually be arbitrary as it searches for `../../Gw2-64.exe`. Are you sure that the addon folder is contained into your GW2 directory? Did you rename the .exe files probably? Also case sensitivity matters.

**Comment by Dave247** [comment]
I didn't touch or change any of the default settings in the installer or do or change anything after the process was completed.... which I just realised was the problem as it was installing to the wrong drive so that was my bad. 😅

Should the installer be smart enough to pick up the game installation directly itself , though if not could that be a feature to be implimented?

**Comment by n1tr0-5urf3r** [comment]
The installer in version v2.52 should now auto-detect the install dir of Gw2-64.exe and set the path accordingly :)
