### ISSUE TITLE
Buttons are gone after discord updated their layout/hud when you click profile

### ISSUE THREAD

**Issue by degu-Tanya** [Maselkov/GW2RPC#36]
Buttons are gone after discord updated their layout/hud when you click profile.
I asked friend if he could see the buttons and he did not, the rest works as normal.

![image](https://github.com/user-attachments/assets/1c55c3dc-18e3-4052-88f1-551953729e1b)

**Comment by n1tr0-5urf3r** [comment]
Do you mean the buttons that link to gw2rpc.info and to the copy/paste website for chatcodes? 
If yes, they've been long gone since v2.5 (July 2022) as Discord dropped support for them in their SDK.

**Comment by degu-Tanya** [comment]
I see, thanks for the information
