### ISSUE TITLE
Add new raid bosses to the registry

### ISSUE THREAD

**Issue by Pluckerpluck** [Maselkov/GW2RPC#8]
I **think** I've done this right:

```
Map ID: 1303

Coagulated Amalgamate: [14208, 15897], 90
Lagos Twins: [14938, 15300], 250
Qadim: [14030, 14857], 200
```

I've tested that in game using your code to read the API and `convert_mumble_coordinates()`, so I think the numbers are valid.

They are such that only the fighting arena is covered (restarting from checkpoint will take you out the area). All bosses.

**Comment by Maselkov** [comment]
There's a PR for this on the repo for the API - https://github.com/mbacalan/gw2rpc-site/pull/1, though the numbers are a bit different and it's missing Qadim

Feel free to check those numbers, maybe open a new PR there, as I have a bit of conflict now :P

Anyhow, that issue is better suited there
