### ISSUE TITLE
Unclear instructions for "launch_gw2_with_rpc.exe"

### ISSUE THREAD

**Issue by nakami** [Maselkov/GW2RPC#9]
On the website you say

> To make starting Rich Presence easier, there is an .exe called launch_gw2_with_rpc.exe included in the download. This script launches both GW2 and the RPC addon. For it to work, it needs to be present in GW2FOLDER\addons\gw2rpc . You may then replace your normal GW2 shortcut with it for ease of launching.

Within the downloaded archive, I have

- config.ini
- gw2rpc.exe
- Launch_GW2_with_RPC.exe

So, now, by saying "For it to work, it needs to be present in GW2FOLDER\addons\gw2rpc" I feel confused. Which of those files do I need to place there now? What about the rest?

**Comment by nakami** [comment]
I looked at the source and came up with the conclusion that you want me to put __all__ files in that directory:

```python3
rpc_path = "gw2rpc.exe"
gw2_64_path = "../../Gw2-64.exe"
gw2_path = "../../Gw2.exe"
```

You may want to make those instructions clear to the broader audience!

**Comment by Maselkov** [comment]
Would be a good idea to make it clearer, yes. That format follows the folder directory some other addons use, which is why I've chosen it.
